export const ErrorCodes = {
  MM_BUILD_FAILED: 'MM_BUILD_FAILED',
  MM_DEPENDENCIES_MISSING: 'MM_DEPENDENCIES_MISSING',

  MM_SESSION_ALREADY_RUNNING: 'MM_SESSION_ALREADY_RUNNING',
  MM_NO_ACTIVE_SESSION: 'MM_NO_ACTIVE_SESSION',
  MM_PAGE_CLOSED: 'MM_PAGE_CLOSED',
  MM_LAUNCH_FAILED: 'MM_LAUNCH_FAILED',

  MM_INVALID_CONFIG: 'MM_INVALID_CONFIG',
  MM_INVALID_INPUT: 'MM_INVALID_INPUT',
  MM_PORT_IN_USE: 'MM_PORT_IN_USE',

  MM_NAVIGATION_FAILED: 'MM_NAVIGATION_FAILED',
  MM_NOTIFICATION_TIMEOUT: 'MM_NOTIFICATION_TIMEOUT',

  MM_TARGET_NOT_FOUND: 'MM_TARGET_NOT_FOUND',
  MM_CLICK_FAILED: 'MM_CLICK_FAILED',
  MM_TYPE_FAILED: 'MM_TYPE_FAILED',
  MM_GETTEXT_FAILED: 'MM_GETTEXT_FAILED',
  MM_WAIT_TIMEOUT: 'MM_WAIT_TIMEOUT',
  MM_CLICK_TIMEOUT: 'MM_CLICK_TIMEOUT', // click action timed out (element found, click hung)
  MM_TYPE_TIMEOUT: 'MM_TYPE_TIMEOUT', // fill action timed out
  MM_GETTEXT_TIMEOUT: 'MM_GETTEXT_TIMEOUT', // textContent action timed out

  MM_SCREENSHOT_FAILED: 'MM_SCREENSHOT_FAILED',

  MM_DISCOVERY_FAILED: 'MM_DISCOVERY_FAILED',
  MM_STATE_FAILED: 'MM_STATE_FAILED',

  MM_KNOWLEDGE_ERROR: 'MM_KNOWLEDGE_ERROR',

  MM_SEED_FAILED: 'MM_SEED_FAILED',
  MM_CONTRACT_NOT_FOUND: 'MM_CONTRACT_NOT_FOUND',

  MM_TAB_NOT_FOUND: 'MM_TAB_NOT_FOUND',

  MM_CAPABILITY_NOT_AVAILABLE: 'MM_CAPABILITY_NOT_AVAILABLE',

  MM_CONTEXT_SWITCH_BLOCKED: 'MM_CONTEXT_SWITCH_BLOCKED',
  MM_SET_CONTEXT_FAILED: 'MM_SET_CONTEXT_FAILED',

  MM_CDP_BLOCKED: 'MM_CDP_BLOCKED',
  MM_CDP_FAILED: 'MM_CDP_FAILED',

  MM_HERMES_FAILED: 'MM_HERMES_FAILED', // underlying device-mcp HERMES_* code is preserved in the message
  MM_HERMES_NOT_AVAILABLE: 'MM_HERMES_NOT_AVAILABLE', // hermes tools require a mobile (iOS/Android) driver

  MM_TOOL_NOT_SUPPORTED_ON_PLATFORM: 'MM_TOOL_NOT_SUPPORTED_ON_PLATFORM', // tool gated off the active platform (browser-only / mobile-only)

  MM_UNKNOWN_TOOL: 'MM_UNKNOWN_TOOL',
  MM_INTERNAL_ERROR: 'MM_INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
